{% set name = "matplotlib-scalebar" %}
{% set version = "0.6.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b0aa1a732c961e1fa50c59b45d0e067977b912d9be3378233081db2a1bd75c20

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - pip
    - python
  run:
    - matplotlib
    - python

test:
  imports:
    - matplotlib_scalebar

about:
  home: "https://github.com/ppinard/matplotlib-scalebar"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Artist for matplotlib to display a scale bar"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
